# Generated by Django 4.1 on 2022-09-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
